meta_product_name: "Bella Bird"
meta_title: "Bella Bird - Making Your Beauty Buying a Breeze."
meta_description: "Find all your beauty favourites in one place, and repurchase your Holy Grail items in one-click!"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
